#ifndef MANTARAY_SHARED_H
#define MANTARAY_SHARED_H

#define HLSS_MANTARAY_AIM_TIME 5.0f
#define HLSS_MANTARAY_SHOOT_TIME 6.0f
#define HLSS_MANTARAY_TIME_DIFFERENCE (HLSS_MANTARAY_SHOOT_TIME - HLSS_MANTARAY_AIM_TIME)

#define HLSS_MANTARAY_LASER_BEAM "sprites/laser.vmt"
#define HLSS_MANTARAY_LASER_LIGHT  "effects/ar2_altfire1.vmt"
#define HLSS_MANTARAY_LASER_LIGHT_BEAM "sprites/lgtning.vmt"

#define HLSS_MANTARAY_LIGHT_RADIUS 8.0f
#define HLSS_MANTARAY_LIGHT_RADIUS_EXTRA 4.0f 

#define HLSS_MANTARAY_LIGHTNING 16.0f

#endif 